apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: revflow-prod
  labels:
    app: revflow
    component: database
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: revflow
      component: database
  template:
    metadata:
      labels:
        app: revflow
        component: database
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: revflow-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: revflow-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: revflow-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: revflow-prod
spec:
  ports:
    - port: 5432
  selector:
    app: revflow
    component: database
