"""tenant_architecture

Revision ID: 39421241c701
Revises: d1e2f3a4b5c6
Create Date: 2026-07-20 22:02:03.315188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39421241c701'
down_revision: Union[str, Sequence[str], None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('business_hours', sa.JSON(), nullable=True),
    sa.Column('booking_rules', sa.JSON(), nullable=True),
    sa.Column('ai_settings', sa.JSON(), nullable=True),
    sa.Column('notification_settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_settings_client_id'), 'client_settings', ['client_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('location_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_client_id'), 'locations', ['client_id'], unique=False)
    op.add_column('appointments', sa.Column('created_by', sa.String(length=128), nullable=True))
    op.add_column('appointments', sa.Column('updated_by', sa.String(length=128), nullable=True))
    op.add_column('appointments', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('appointments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('audit_logs', sa.Column('created_by', sa.String(length=128), nullable=True))
    op.add_column('audit_logs', sa.Column('updated_by', sa.String(length=128), nullable=True))
    op.add_column('audit_logs', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('audit_logs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('call_attempts', sa.Column('created_by', sa.String(length=128), nullable=True))
    op.add_column('call_attempts', sa.Column('updated_by', sa.String(length=128), nullable=True))
    op.add_column('call_attempts', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('call_attempts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('calls', sa.Column('created_by', sa.String(length=128), nullable=True))
    op.add_column('calls', sa.Column('updated_by', sa.String(length=128), nullable=True))
    op.add_column('calls', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('calls', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clients', sa.Column('uuid', sa.String(length=36), server_default=sa.text("gen_random_uuid()::text"), nullable=False))
    op.alter_column('clients', 'name', new_column_name='clinic_name')
    op.alter_column('clients', 'subdomain', new_column_name='slug')
    op.add_column('clients', sa.Column('business_email', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('logo', sa.String(length=500), nullable=True))
    op.add_column('clients', sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False))
    op.add_column('clients', sa.Column('country', sa.String(length=50), server_default='US', nullable=False))
    op.add_column('clients', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('clients', sa.Column('specialty', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('subscription_plan', sa.String(length=50), server_default='free', nullable=False))
    op.add_column('clients', sa.Column('subscription_status', sa.String(length=50), server_default='active', nullable=False))
    op.add_column('clients', sa.Column('max_users', sa.Integer(), server_default='5', nullable=False))
    op.add_column('clients', sa.Column('max_locations', sa.Integer(), server_default='1', nullable=False))
    op.alter_column('clients', 'is_active', new_column_name='active')
    op.add_column('clients', sa.Column('created_by', sa.String(length=128), nullable=True))
    op.add_column('clients', sa.Column('updated_by', sa.String(length=128), nullable=True))
    op.add_column('clients', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('clients', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_clients_subdomain'), table_name='clients')
    op.create_index(op.f('ix_clients_slug'), 'clients', ['slug'], unique=True)
    op.create_index(op.f('ix_clients_uuid'), 'clients', ['uuid'], unique=True)
    op.drop_column('clients', 'phone_number')
    
    
    op.drop_column('clients', 'logo_url')
    
    op.add_column('email_verifications', sa.Column('created_by', sa.String(length=128), nullable=True))
    op.add_column('email_verifications', sa.Column('updated_by', sa.String(length=128), nullable=True))
    op.add_column('email_verifications', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('email_verifications', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('password_resets', sa.Column('created_by', sa.String(length=128), nullable=True))
    op.add_column('password_resets', sa.Column('updated_by', sa.String(length=128), nullable=True))
    op.add_column('password_resets', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('password_resets', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('permissions', sa.Column('created_by', sa.String(length=128), nullable=True))
    op.add_column('permissions', sa.Column('updated_by', sa.String(length=128), nullable=True))
    op.add_column('permissions', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('permissions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('role_permissions', sa.Column('created_by', sa.String(length=128), nullable=True))
    op.add_column('role_permissions', sa.Column('updated_by', sa.String(length=128), nullable=True))
    op.add_column('role_permissions', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('role_permissions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('roles', sa.Column('created_by', sa.String(length=128), nullable=True))
    op.add_column('roles', sa.Column('updated_by', sa.String(length=128), nullable=True))
    op.add_column('roles', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('roles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_roles', sa.Column('created_by', sa.String(length=128), nullable=True))
    op.add_column('user_roles', sa.Column('updated_by', sa.String(length=128), nullable=True))
    op.add_column('user_roles', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_roles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_sessions', sa.Column('created_by', sa.String(length=128), nullable=True))
    op.add_column('user_sessions', sa.Column('updated_by', sa.String(length=128), nullable=True))
    op.add_column('user_sessions', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_sessions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('user_sessions', 'deleted_at')
    op.drop_column('user_sessions', 'is_deleted')
    op.drop_column('user_sessions', 'updated_by')
    op.drop_column('user_sessions', 'created_by')
    op.drop_column('user_roles', 'deleted_at')
    op.drop_column('user_roles', 'is_deleted')
    op.drop_column('user_roles', 'updated_by')
    op.drop_column('user_roles', 'created_by')
    op.drop_column('roles', 'deleted_at')
    op.drop_column('roles', 'is_deleted')
    op.drop_column('roles', 'updated_by')
    op.drop_column('roles', 'created_by')
    op.drop_column('role_permissions', 'deleted_at')
    op.drop_column('role_permissions', 'is_deleted')
    op.drop_column('role_permissions', 'updated_by')
    op.drop_column('role_permissions', 'created_by')
    op.drop_column('permissions', 'deleted_at')
    op.drop_column('permissions', 'is_deleted')
    op.drop_column('permissions', 'updated_by')
    op.drop_column('permissions', 'created_by')
    op.drop_column('password_resets', 'deleted_at')
    op.drop_column('password_resets', 'is_deleted')
    op.drop_column('password_resets', 'updated_by')
    op.drop_column('password_resets', 'created_by')
    op.drop_column('email_verifications', 'deleted_at')
    op.drop_column('email_verifications', 'is_deleted')
    op.drop_column('email_verifications', 'updated_by')
    op.drop_column('email_verifications', 'created_by')
    op.add_column('clients', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('subdomain', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_clients_uuid'), table_name='clients')
    op.drop_index(op.f('ix_clients_slug'), table_name='clients')
    op.create_index(op.f('ix_clients_subdomain'), 'clients', ['subdomain'], unique=True)
    op.drop_column('clients', 'deleted_at')
    op.drop_column('clients', 'is_deleted')
    op.drop_column('clients', 'updated_by')
    op.drop_column('clients', 'created_by')
    op.drop_column('clients', 'active')
    op.drop_column('clients', 'max_locations')
    op.drop_column('clients', 'max_users')
    op.drop_column('clients', 'subscription_status')
    op.drop_column('clients', 'subscription_plan')
    op.drop_column('clients', 'specialty')
    op.drop_column('clients', 'address')
    op.drop_column('clients', 'country')
    op.drop_column('clients', 'currency')
    op.drop_column('clients', 'logo')
    op.drop_column('clients', 'website')
    op.drop_column('clients', 'phone')
    op.drop_column('clients', 'business_email')
    op.drop_column('clients', 'slug')
    op.drop_column('clients', 'clinic_name')
    op.drop_column('clients', 'uuid')
    op.drop_column('calls', 'deleted_at')
    op.drop_column('calls', 'is_deleted')
    op.drop_column('calls', 'updated_by')
    op.drop_column('calls', 'created_by')
    op.drop_column('call_attempts', 'deleted_at')
    op.drop_column('call_attempts', 'is_deleted')
    op.drop_column('call_attempts', 'updated_by')
    op.drop_column('call_attempts', 'created_by')
    op.drop_column('audit_logs', 'deleted_at')
    op.drop_column('audit_logs', 'is_deleted')
    op.drop_column('audit_logs', 'updated_by')
    op.drop_column('audit_logs', 'created_by')
    op.drop_column('appointments', 'deleted_at')
    op.drop_column('appointments', 'is_deleted')
    op.drop_column('appointments', 'updated_by')
    op.drop_column('appointments', 'created_by')
    op.drop_index(op.f('ix_locations_client_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_client_settings_client_id'), table_name='client_settings')
    op.drop_table('client_settings')
    # ### end Alembic commands ###
